// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: proto/max.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnIfMaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *ReturnIfMaxRequest) Reset() {
	*x = ReturnIfMaxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_max_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnIfMaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnIfMaxRequest) ProtoMessage() {}

func (x *ReturnIfMaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_max_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnIfMaxRequest.ProtoReflect.Descriptor instead.
func (*ReturnIfMaxRequest) Descriptor() ([]byte, []int) {
	return file_proto_max_proto_rawDescGZIP(), []int{0}
}

func (x *ReturnIfMaxRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ReturnIfMaxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxTillNow int32 `protobuf:"varint,1,opt,name=maxTillNow,proto3" json:"maxTillNow,omitempty"`
}

func (x *ReturnIfMaxResponse) Reset() {
	*x = ReturnIfMaxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_max_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnIfMaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnIfMaxResponse) ProtoMessage() {}

func (x *ReturnIfMaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_max_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnIfMaxResponse.ProtoReflect.Descriptor instead.
func (*ReturnIfMaxResponse) Descriptor() ([]byte, []int) {
	return file_proto_max_proto_rawDescGZIP(), []int{1}
}

func (x *ReturnIfMaxResponse) GetMaxTillNow() int32 {
	if x != nil {
		return x.MaxTillNow
	}
	return 0
}

var File_proto_max_proto protoreflect.FileDescriptor

var file_proto_max_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x26, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x66, 0x4d, 0x61, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x35, 0x0a, 0x13, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x49, 0x66, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x54, 0x69, 0x6c, 0x6c, 0x4e, 0x6f, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x54, 0x69, 0x6c, 0x6c, 0x4e, 0x6f, 0x77,
	0x32, 0x54, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x66, 0x4d, 0x61, 0x78, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x49, 0x66, 0x4d, 0x61, 0x78, 0x12, 0x13, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x66,
	0x4d, 0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x49, 0x66, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_max_proto_rawDescOnce sync.Once
	file_proto_max_proto_rawDescData = file_proto_max_proto_rawDesc
)

func file_proto_max_proto_rawDescGZIP() []byte {
	file_proto_max_proto_rawDescOnce.Do(func() {
		file_proto_max_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_max_proto_rawDescData)
	})
	return file_proto_max_proto_rawDescData
}

var file_proto_max_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_max_proto_goTypes = []interface{}{
	(*ReturnIfMaxRequest)(nil),  // 0: ReturnIfMaxRequest
	(*ReturnIfMaxResponse)(nil), // 1: ReturnIfMaxResponse
}
var file_proto_max_proto_depIdxs = []int32{
	0, // 0: ReturnIfMaxService.ReturnIfMax:input_type -> ReturnIfMaxRequest
	1, // 1: ReturnIfMaxService.ReturnIfMax:output_type -> ReturnIfMaxResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_max_proto_init() }
func file_proto_max_proto_init() {
	if File_proto_max_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_max_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnIfMaxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_max_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnIfMaxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_max_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_max_proto_goTypes,
		DependencyIndexes: file_proto_max_proto_depIdxs,
		MessageInfos:      file_proto_max_proto_msgTypes,
	}.Build()
	File_proto_max_proto = out.File
	file_proto_max_proto_rawDesc = nil
	file_proto_max_proto_goTypes = nil
	file_proto_max_proto_depIdxs = nil
}
